name: CI - Clients API

on:
  push:
    branches: [develop, main, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients-api  # <-- corriger ici si besoin

    steps:
    - uses: actions/checkout@v4

    - run: ls -al  # debug pour confirmer le nom du dossier

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: PTK_client_api/package-lock.json  # mettre le bon chemin

    - run: npm install
    - run: npm run build
    - run: npm test
