name: CI - Clients API

on:
  push:
    branches: [develop, main, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # On ne met rien ici pour ne pas bloquer sur un mauvais dossier
        # On choisira le working-directory dans les étapes où c'est nécessaire
        # working-directory: ./PKT_client_api

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Debug - Affiche le chemin courant et contenu racine
      run: |
        echo "Répertoire courant : $(pwd)"
        echo "Contenu du dossier racine :"
        ls -al

    - name: Debug - Recherche dossier client API
      run: |
        echo "Recherche des dossiers dans le repo :"
        ls -al

    # Ajuste ici le chemin selon ce que tu trouves dans le debug
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: PKT_client_api/package-lock.json

    - name: Install dependencies
      run: npm install
      working-directory: ./PKT_client_api

    - name: Build
      run: npm run build
      working-directory: ./PKT_client_api

    - name: Run tests
      run: npm test
      working-directory: ./PKT_client_api
