name: Vérification structure projet

on:
  push:
    branches:
      - main

jobs:
  check-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Afficher la structure du projet avec tree
        run: |
          if command -v tree > /dev/null; then
            tree
          else
            echo "tree n'est pas installé, affichage avec ls -R"
            ls -R
          fi

      - name: Afficher Hello World
        run: echo "Hello World"
